{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled (ne $svc.kind "worker") $svc.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: venueops-{{ $name | kebabcase }}
  labels:
    app.kubernetes.io/name: venueops
    app.kubernetes.io/component: {{ $name | kebabcase }}
    app.kubernetes.io/part-of: venueops-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: venueops-{{ $name | kebabcase }}
  minReplicas: {{ $svc.autoscaling.minReplicas }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $svc.autoscaling.cpuUtilization }}
---
{{- end }}
{{- end }}
