apiVersion: v1
kind: ServiceAccount
metadata:
  name: venueops-workload
  labels:
    {{- include "venueops.labels" . | nindent 4 }}
  {{- if .Values.global.workloadIdentity.enabled }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentity.clientId | quote }}
  {{- end }}
automountServiceAccountToken: true
