server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;

    location = /health.html {
        access_log off;
    }

    location /api/ {
        proxy_pass http://venueops-api:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ingestion/ {
        proxy_pass http://venueops-ingestion-api:8001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /aiops/ {
        default_type application/json;
        return 503 '{"status":"down","service":"aiops","message":"AI Ops is not deployed in Phase 1"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
